<?php


class QiniuFilesystemServiceProvider extends \think\Service
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}